# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31a2e81d4204cfd2ca7021c2fa4329bb450f17665b7021ed6b4af022e4719352a411df089fb84a33a27237b461f4e382d653631346657e1d539f1766d9283d8f

test:
  secret_key_base: f51a6a9b340d4f26dd35a99b0e88156e17522960d253e9512ea0c7668a801b6861755187f75d3a089cc324778f6446f210dcb293c2eaa986a65d8b976fc0c66f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
